### ISSUE TITLE
Android dependency versioning suggestion does not fit with proper Android build reproduction steps

### ISSUE THREAD

**Issue by josephmbeveridge** [BranchMetrics/documentation#182]
In the sdk integration steps it is suggested to:
`Add compile 'io.branch.sdk.android:library:1.+' to the dependencies section of your build.gradle file.`

This does not fit with the recommendations for making reliable Android builds using CI as breaking changes to the sdk would break CI. The gradle dependency should be versioned, i.e. `compile 'io.branch.sdk.android:library:1.10.5'`.

If you decide not to do it this way, it would be nice if the current version code was listed there so that you don't have to download the jars or go to the github repo and look at the releases to see the most recent release version.

**Comment by Sarkar** [comment]
hello @josephmbeveridge! you bring up a good point - we intentionally left this as such because of the frequent release nature of our SDKs.

We try our hardest to never introduce breaking changes, and in fact, you can absolutely use version - we just simply chose to have the `+` present as a convenience. I like the idea of current version code - I'll save it on our asana and see if we can get a nice and easy way in there.
